inventi/eventstore-tools

src/main/kotlin/io/inventi/eventstore/eventhandler/config/EventStoreProperties.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inventi/eventstore-tools/5)

feat: Change eventstore configuration

---

README.md
src/main/kotlin/io/inventi/eventstore/publisher/EventPublisher.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inventi/eventstore-tools/11)

Feat/bo 648/create event publisher

---

src/main/kotlin/io/inventi/eventstore/eventhandler/model/EventData.kt
src/main/kotlin/io/inventi/eventstore/eventhandler/model/EventOperation.kt
src/main/kotlin/io/inventi/eventstore/eventhandler/model/EventOperationStatus.kt
src/main/kotlin/io/inventi/eventstore/publisher/EventPublisher.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inventi/eventstore-tools/16)

feat: publish event operation together with event to ES

---

build.gradle
src/main/kotlin/io/inventi/eventstore/eventhandler/EventHandlerExtension.kt
src/main/kotlin/io/inventi/eventstore/eventhandler/IdempotentEventHandler.kt
src/main/kotlin/io/inventi/eventstore/eventhandler/IdempotentPersistentSubscriptionListener.kt
src/main/kotlin/io/inventi/eventstore/eventhandler/tracing/TracingExtension.kt
src/main/kotlin/io/inventi/eventstore/eventtracing/TraceContextExtractor.kt
src/main/kotlin/io/inventi/eventstore/eventtracing/TraceContextInjector.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inventi/eventstore-tools/18)

feat(BO-1039): handle event tracing propagation

---

src/main/kotlin/io/inventi/eventstore/eventhandler/IdempotentEventHandler.kt
src/main/kotlin/io/inventi/eventstore/eventhandler/config/EventStoreConfig.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inventi/eventstore-tools/24)

feat(BOS-116): allow configuring max operation retries

---

build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inventi/eventstore-tools/25)

fix(BOS-130): bump esjc version

---

src/main/kotlin/io/inventi/eventstore/eventhandler/IdempotentEventHandler.kt
src/main/kotlin/io/inventi/eventstore/eventhandler/config/EventStoreConfig.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inventi/eventstore-tools/27)

feat(BO-1332): make min checkpoint count configurable and default to 10

---

build.gradle
gradle.properties

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inventi/eventstore-tools/29)

fix(BO-1332): do not autoconfigure redis

---

src/main/kotlin/io/inventi/eventstore/util/script/CopyAndReplaceUtils.kt
src/main/kotlin/io/inventi/eventstore/util/script/JsonUtils.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inventi/eventstore-tools/30)

Feat/bo 1333/add copy and replace tools

---

src/main/kotlin/io/inventi/eventstore/util/script/CopyAndReplaceUtils.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inventi/eventstore-tools/31)

fix(BOS-167): append to empty object if event has no metadata

---

src/main/kotlin/io/inventi/eventstore/eventhandler/IdempotentPersistentSubscriptionListener.kt
src/main/kotlin/io/inventi/eventstore/eventhandler/model/EventIds.kt
src/main/kotlin/io/inventi/eventstore/eventhandler/model/MethodParametersType.kt
src/test/kotlin/io/inventi/eventstore/eventhandler/IdempotentPersistentSubscriptionListenerTest.kt
src/test/kotlin/io/inventi/eventstore/eventhandler/events/a/MetadataA.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inventi/eventstore-tools/32)

feat(BO-1604): add event ids as method param

---

build.gradle

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inventi/eventstore-tools/33)

chore(BO-1583): bump dependency versions

---

build.gradle.kts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inventi/eventstore-tools/35)

chore(BO-1628): bump spring boot and gcp starter versions

---

src/main/kotlin/io/inventi/eventstore/util/script/CopyAndReplaceUtils.kt

1. Events became too big and 10 sec is not enough to to append events
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inventi/eventstore-tools/38)

feat(BO-1807): configure heartbeat and operation timeouts

---

README.md
build.gradle.kts
src/main/kotlin/io/inventi/eventstore/eventhandler/InitialPosition.kt
src/main/kotlin/io/inventi/eventstore/eventhandler/LoggingExtension.kt
src/main/kotlin/io/inventi/eventstore/eventhandler/PersistentSubscriptions.kt
src/main/kotlin/io/inventi/eventstore/eventhandler/tracing/TracingExtension.kt
src/test/kotlin/io/inventi/eventstore/eventhandler/CatchupSubscriptionsIntegrationTest.kt
src/test/kotlin/io/inventi/eventstore/eventhandler/PersistentSubscriptionsIntegrationTest.kt
src/test/kotlin/io/inventi/eventstore/eventhandler/PersistentSubscriptionsTest.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inventi/eventstore-tools/41)

Feat/bo 1808/automatic persistent subscription retry

---

src/main/kotlin/io/inventi/eventstore/eventhandler/EventIdempotencyStorage.kt
src/main/kotlin/io/inventi/eventstore/eventhandler/util/RecordedEventExtensions.kt
src/main/kotlin/io/inventi/eventstore/util/script/CopyAndReplaceUtils.kt
src/test/kotlin/io/inventi/eventstore/eventhandler/EventIdempotencyStorageTest.kt
src/test/kotlin/io/inventi/eventstore/eventhandler/dao/ProcessedEventDaoTest.kt
src/test/kotlin/io/inventi/eventstore/eventhandler/events/TestMetadata.kt
src/test/kotlin/io/inventi/eventstore/eventhandler/util/DataBuilder.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inventi/eventstore-tools/43)

feat(BO-2045): allow to replace event types in scripts

---

src/main/kotlin/io/inventi/eventstore/Subscriptions.kt
src/main/kotlin/io/inventi/eventstore/eventhandler/CatchupSubscriptions.kt
src/test/kotlin/io/inventi/eventstore/EventStoreIntegrationTest.kt
src/test/kotlin/io/inventi/eventstore/eventhandler/CatchupSubscriptionsMeterRegistryIntegrationTest.kt
src/test/kotlin/io/inventi/eventstore/eventhandler/util/WithMeterRegistryAssertions.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inventi/eventstore-tools/44)

feat(BOS-285): drop catchup subscriptions on unexpected error

---

build.gradle.kts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inventi/eventstore-tools/45)

chore(BOS-300): bump esjc version to 2.5.0

---

src/main/kotlin/io/inventi/eventstore/eventhandler/CatchupSubscriptionState.kt
src/main/kotlin/io/inventi/eventstore/eventhandler/CatchupSubscriptions.kt
src/main/kotlin/io/inventi/eventstore/eventhandler/PersistentSubscriptionState.kt
src/main/kotlin/io/inventi/eventstore/eventhandler/PersistentSubscriptions.kt
src/main/kotlin/io/inventi/eventstore/eventhandler/Subscriptions.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inventi/eventstore-tools/49)

fix(BOS-310): ignore subscription stoppage timeouts

---

src/main/kotlin/io/inventi/eventstore/eventhandler/CatchupSubscriptionState.kt
src/main/kotlin/io/inventi/eventstore/eventhandler/CatchupSubscriptions.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/inventi/eventstore-tools/50)

chore(BOS-319): log catch up subscription update and drop
